"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const simpleTranslations: Record<Language, Record<string, string>> = {
  en: {
    "brand-title": "Anshu Computer",
    "brand-sub": "& Tax Consultancy",
    "nav-services": "Services",
    "nav-book": "Book Desk",
    "nav-creed": "Our Creed",
    "nav-process": "Filing Roadmap",
    "nav-contact": "Direct Desk",
    "nav-cta": "WhatsApp Dispatch",
    "hero-badge-rating": "5.0 Rating",
    "hero-badge-reviews": "23 Verified Google Maps Endorsements",
    "hero-badge-loc": "Serving Nationally",
    "hero-title-main": "Anshu Computer &",
    "hero-title-accent": "Tax Consultancy",
    "hero-desc": "Delivering ironclad Provident Fund (PF) resolutions, absolute compliance in Tax filing (ITR & GST), and precision-based citizen portal services across the country.",
    "hero-cta-booking": "Schedule Appointment / Callback",
    "hero-cta-whatsapp": "WhatsApp Chat",
    "efficiency-title": "Filing Efficiency Comparison",
    "efficiency-desc": "Why business owners trust Anshu Computer over uncertified digital cafes.",
    "efficiency-badge": "Metrics",
    "table-h-param": "Consultation Parameter",
    "table-h-anshu": "Anshu Computer Desk",
    "table-h-cafes": "Uncertified Public Cafes",
    "table-r1-p": "PF Mismatch Remediation",
    "table-r1-a": "End-to-end processing & claim linking",
    "table-r1-c": "Basic submissions (No errors resolved)",
    "table-r2-p": "ITR & Computation Verification",
    "table-r2-a": "Dual-phase manual calculation audit",
    "table-r2-c": "Automated system uploads (Prone to errors)",
    "table-r3-p": "Emergency Support Lines",
    "table-r3-a": "Direct priority WhatsApp helpline",
    "table-r3-c": "No support after payment",
    "booking-badge": "Dispatch Desk",
    "booking-title": "Consultation Dispatch",
    "booking-desc": "Select your request type. The form will generate a pre-formatted message sent directly to our secure WhatsApp line.",
    "form-label-name": "Your Full Name",
    "form-placeholder-name": "Enter name",
    "form-label-phone": "Mobile Number",
    "form-placeholder-phone": "Enter 10 digit mobile number",
    "form-label-service": "Service Required",
    "form-opt-service-default": "Select service",
    "form-opt-service-pf": "PF Consultancy (Disputes, claims, mismatch)",
    "form-opt-service-itr": "Income Tax Return (ITR)",
    "form-opt-service-gst": "GST (Registration / Filing)",
    "form-label-request": "Request Type",
    "form-opt-request-callback": "Request Callback",
    "form-opt-request-appt": "Schedule Appointment",
    "form-label-datetime": "Proposed Appointment Date & Time",
    "form-btn-submit": "Dispatch to WhatsApp Line",
    "services-badge": "Excellence Directory",
    "services-title": "Core Advisory & Digital Services",
    "services-desc": "Meticulously organized disciplines engineered to deliver error-free filings and structural safety.",
    "card1-badge": "Primary Specialty",
    "card1-title": "Specialized Provident Fund (PF) Consultancy",
    "card1-desc": "Untangling critical, high-friction EPF issues that keep workers and organizations separated from their rightful balance.",
    "card1-btn": "Query EPF Issue Now",
    "card1-sub1-title": "Mismatch Remediation",
    "card1-sub1-desc": "Systematic filing of joint declarations to correct names, date of birth mismatches, and father's name errors on the EPFO portal.",
    "card1-sub2-title": "EPF Claim Settle",
    "card1-sub2-desc": "Expert execution of pension withdrawals (Form 10C), full settlement (Form 19), advance PF claims, and transfer schemes.",
    "card1-sub3-title": "UAN Consolidation",
    "card1-sub3-desc": "Merging multiple old UAN balances into a single active account and facilitating safe KYC (PAN, Aadhaar, Bank) mapping.",
    "card1-sub4-title": "Ex-Employer Cases",
    "card1-sub4-desc": "Coordinating and settling claims where previous employers are permanently closed or non-cooperative.",
    "card2-badge": "Compliance",
    "card2-title": "Taxation Services",
    "card2-desc": "Meticulous filing and calculation audits designed to minimize tax notice liabilities for individuals and small operations.",
    "card2-sub1": "<strong>ITR Filing (Salaried & Commercial):</strong> Correct computation sheets mapping every income source.",
    "card2-sub2": "<strong>GST Registration Setup:</strong> Document screening to secure GST numbers with minimal delay.",
    "card2-sub3": "<strong>GST Returns Loop:</strong> Timely filing of GSTR-1 & GSTR-3B with integrated input credit matches.",
    "card2-footer-text": "Regular & Annual returns",
    "card2-footer-btn": "Request Filing",
    "card3-badge": "Digital Hub",
    "card3-title": "Digital & Citizen Services",
    "card3-desc": "Expedited digital workflow solutions handling daily web tasks with speed and verification confirmation.",
    "card3-sub1": "<strong>Life Certificates (Jeevan Pramaan):</strong> Direct biometric generation for senior pensioners.",
    "card3-sub2": "<strong>Government Citizen Registrations:</strong> Handling portals and portal correction claims securely.",
    "card3-sub3": "<strong>Frictionless Document Scanning:</strong> Organized compilation of high-fidelity scanned assets.",
    "card3-footer-text": "Secure digital execution",
    "card3-footer-btn": "Access Desk",
    "process-badge": "Methodology",
    "process-title": "Filing Roadmap",
    "process-desc": "Our standardized process that guarantees double-checked compliance on every single application we process.",
    "process-step1-title": "Document Vaulting",
    "process-step1-desc": "We collect your credentials (Aadhaar, PAN, Form-16, previous invoices) safely via WhatsApp or direct office handover.",
    "process-step2-title": "Audit Computation",
    "process-step2-desc": "Your file is assessed and structured using specialized tax spreadsheets, checking for potential errors or mismatch risks.",
    "process-step3-title": "System Clearance",
    "process-step3-desc": "We file the finalized data systematically on official portals (EPFO or Income Tax India website).",
    "process-step4-title": "Dispatched Receipt",
    "process-step4-desc": "You receive official PDFs, verification IDs, and filing receipts directly on your WhatsApp for safe future archiving.",
    "creed-badge": "Our Creed",
    "creed-title": "Valuing Your Time Sovereignty.",
    "creed-desc": "In our view, compliance is not just about avoiding regulatory complications—it is about restoring and protecting your valuable business time. We built our entire service loop on strict procedural rules to save you from long hold lines and administrative delays.",
    "creed-quote": "\"We deliver absolute zero margin for simple, preventable human errors so you can focus entirely on growth.\"",
    "creed-col1-num": "01",
    "creed-col2-num": "02",
    "creed-col3-num": "03",
    "creed-col4-num": "04",
    "creed-col1-title": "Operational Efficiency",
    "creed-col1-desc": "We leverage clean, structured documentation systems. When files are delivered to our desk, processing starts immediately with zero backlog.",
    "creed-col2-title": "Meticulous Auditing",
    "creed-col2-desc": "All computation sheets, Form applications, and registration logs undergo cross-validation. Redundancy checks protect you from filing setbacks.",
    "creed-col3-title": "Local Integrity",
    "creed-col3-desc": "While our operational desk is based in Uttar Pradesh, we utilize high-fidelity digital systems to coordinate and resolve filings for clients nationwide.",
    "creed-col4-title": "Up-to-Date Systems",
    "creed-col4-desc": "Tax portals change algorithms and laws constantly. We verify state updates daily, keeping client systems fully aligned and ready.",
    "standing-badge": "Local Verification",
    "standing-title": "Our Location & Standing",
    "standing-desc": "Proudly serving the local community of Orai and digital clients nationwide with an established tracking index of 23 positive, verified Google Maps Reviews.",
    "standing-card-title": "Kaushal Market, Orai",
    "standing-card-desc": "Accessible market location",
    "standing-card-reviews": "23 Google Reviews",
    "contact-title": "Direct Advisory Desk",
    "contact-addr-label": "Office Location",
    "contact-addr-val": "Anshu Computer and Tax Consultancy<br/>Kaushal Market, Rath Road, Orai,<br/>Uttar Pradesh, 285001",
    "contact-hours-label": "Office Hours",
    "contact-hours-val": "Monday – Saturday: 11:00 AM – 06:00 PM",
    "contact-hours-sub": "Sundays & Public Holidays: Offline",
    "contact-email-label": "Electronic Mail",
    "contact-whatsapp-btn": "WhatsApp Dispatch",
    "contact-whatsapp-sub": "Response priority: Within 30 minutes during standard office operational hours.",
    "footer-desc": "Professional regulatory and compliance agency. Assisting our clients with strict accuracy since establishment.",
    "footer-access-title": "Direct Access",
    "footer-copyright": "© 2026 Anshu Computer and Tax Consultancy. All rights reserved.",
    "footer-national-badge": "Trusted National Consultant",
    "footer-loc-badge": "Kaushal Market, Orai, UP",
    "toggle-lang-label": "हिन्दी"
  },
  hi: {
    "brand-title": "अंशु कंप्यूटर",
    "brand-sub": "और टैक्स कंसल्टेंसी",
    "nav-services": "हमारी सेवाएं",
    "nav-book": "अपॉइंटमेंट लें",
    "nav-creed": "हमारा उद्देश्य",
    "nav-process": "कैसे काम होगा?",
    "nav-contact": "संपर्क करें",
    "nav-cta": "WhatsApp पर बात करें",
    "hero-badge-rating": "5.0 Rating",
    "hero-badge-reviews": "Google Maps पर 23 अच्छे Reviews",
    "hero-badge-loc": "पूरे भारत में सर्विस",
    "hero-title-main": "Anshu Computer &",
    "hero-title-accent": "Tax Consultancy",
    "hero-desc": "हम पूरे भारत में PF (भविष्य निधि), ITR (इनकम टैक्स रिटर्न), GST और सभी सरकारी डिजिटल काम बिना किसी गलती के आसानी से सुलझाते हैं।",
    "hero-cta-booking": "Appointment या Call के लिए मैसेज भेजें",
    "hero-cta-whatsapp": "WhatsApp चैट शुरू करें",
    "efficiency-title": "हमारा काम करने का तरीका क्यों बेहतर है?",
    "efficiency-desc": "क्यों लोग सामान्य साइबर कैफे के बजाय अंशु कंप्यूटर पर भरोसा करते हैं।",
    "efficiency-badge": "विशेषताएं",
    "table-h-param": "काम की तुलना (Parameters)",
    "table-h-anshu": "Anshu Computer डेस्क",
    "table-h-cafes": "सामान्य साइबर कैफे",
    "table-r1-p": "PF की गलतियां सुधारना (Name/DOB Mismatch)",
    "table-r1-a": "पूरा काम और पैसे निकालने (Claim) तक पूरी मदद",
    "table-r1-c": "सिर्फ फॉर्म भर देना (कोई गलती नहीं सुलझाना)",
    "table-r2-p": "ITR (इनकम टैक्स रिटर्न) और ऑडिट",
    "table-r2-a": "डबल-चेक करके बिना किसी गलती के रिटर्न भरना",
    "table-r2-c": "जल्दबाजी में ऑनलाइन भर देना (गलतियों का डर)",
    "table-r3-p": "Urgent सपोर्ट (Emergency Help)",
    "table-r3-a": "WhatsApp पर सीधी बात और तुरंत रिप्लाई",
    "table-r3-c": "पैसे लेने के बाद कोई रिस्पांस नहीं देना",
    "booking-badge": "हेल्प डेस्क",
    "booking-title": "Call या Appointment के लिए मैसेज भेजें",
    "booking-desc": "नीचे अपनी डिटेल्स भरें। यह फॉर्म सीधे आपके व्हाट्सएप से हमारे नंबर पर एक मैसेज भेज देगा।",
    "form-label-name": "आपका नाम (Name)",
    "form-placeholder-name": "अपना नाम लिखें",
    "form-label-phone": "मोबाइल नंबर (Mobile No.)",
    "form-placeholder-phone": "अपना 10 अंकों का मोबाइल नंबर लिखें",
    "form-label-service": "क्या काम है? (Select Service)",
    "form-opt-service-default": "काम चुनें",
    "form-opt-service-pf": "PF का काम (विवाद, पैसे निकालना, सुधार)",
    "form-opt-service-itr": "ITR भरना (Income Tax Return)",
    "form-opt-service-gst": "GST का काम (नया रजिस्ट्रेशन या रिटर्न)",
    "form-label-request": "आप क्या चाहते हैं?",
    "form-opt-request-callback": "फ़ोन पर बात करना चाहते हैं (Callback)",
    "form-opt-request-appt": "ऑफिस आकर मिलना चाहते हैं (Appointment)",
    "form-label-datetime": "मिलने की तारीख और समय (Date & Time)",
    "form-btn-submit": "WhatsApp पर सीधे भेजें (Send to WhatsApp)",
    "services-badge": "हमारी सर्विसेज़",
    "services-title": "PF, Tax और सभी डिजिटल सर्विसेज़",
    "services-desc": "बिना किसी गलती के समय पर आपका काम पूरा करने की हमारी गारंटी।",
    "card1-badge": "सबसे मुख्य काम",
    "card1-title": "PF (भविष्य निधि) की सभी समस्याओं का हल",
    "card1-desc": "PF से जुड़ी हर समस्या का पक्का समाधान, ताकि आपका अटका हुआ पैसा सुरक्षित वापस मिल सके।",
    "card1-btn": "WhatsApp पर PF की समस्या बताएं",
    "card1-sub1-title": "PF में नाम/जन्म तारीख सुधारना (Name/DOB Mismatch)",
    "card1-sub1-desc": "EPFO पोर्टल पर नाम, जन्म तिथि या पिता का नाम गलत होने पर Joint Declaration फॉर्म द्वारा सही सुधार।",
    "card1-sub2-title": "PF का पैसा निकालना (Claim Settlement)",
    "card1-sub2-desc": "पेंशन का पैसा (Form 10C), पूरा PF निकालना (Form 19), बीमारी या शादी के लिए एडवांस PF और पीएफ ट्रांसफर का काम।",
    "card1-sub3-title": "UAN मर्ज और KYC करना",
    "card1-sub3-desc": "पुराने सभी पीएफ खातों को एक नए UAN में ट्रांसफर करना और पैन, आधार व बैंक को सुरक्षित तरीके से लिंक करना।",
    "card1-sub4-title": "पुरानी कंपनी बंद या असहयोगी होने पर (Ex-Employer Issues)",
    "card1-sub4-desc": "अगर पुरानी कंपनी बंद हो गई है या साइन नहीं कर रही, तो भी आपका अटका हुआ पैसा निकालने में पूरी मदद।",
    "card2-badge": "टैक्स सर्विस",
    "card2-title": "Income Tax और GST का काम",
    "card2-desc": "समय पर सही गणना के साथ टैक्स फाइलिंग ताकि आपको कोई सरकारी नोटिस या पेनल्टी न मिले।",
    "card2-sub1": "<strong>ITR फाइलिंग (वेतन और बिजनेस):</strong> सरकारी नियमों के तहत टैक्स बचाते हुए सुरक्षित इनकम टैक्स रिटर्न (ITR) भरना।",
    "card2-sub2": "<strong>GST रजिस्ट्रेशन:</strong> सभी जरूरी दस्तावेजों की जांच कर बिना किसी परेशानी के नया GST नंबर प्राप्त करना।",
    "card2-sub3": "<strong>GST रिटर्न फाइलिंग:</strong> हर महीने समय पर GSTR-1 व GSTR-3B भरना और इनपुट टैक्स क्रेडिट (ITC) का मिलान।",
    "card2-footer-text": "नियमित टैक्स काम (Tax Compliance)",
    "card2-footer-btn": "फाइलिंग शुरू करें",
    "card3-badge": "डिजिटल काम",
    "card3-title": "ऑनलाइन सरकारी और जरूरी सर्विसेज़",
    "card3-desc": "रोजमर्रा के जरूरी ऑनलाइन फॉर्म और अन्य सरकारी योजनाओं के आवेदन तेजी और सुरक्षित तरीके से।",
    "card3-sub1": "<strong>डिजिटल जीवन प्रमाण (Life Certificate):</strong> पेंशनभोगियों के लिए फिंगरप्रिंट मशीन द्वारा तुरंत डिजिटल जीवन प्रमाण पत्र बनाना।",
    "card3-sub2": "<strong>सरकारी योजनाएं व सुधार:</strong> विभिन्न सरकारी पोर्टलों पर नए पंजीकरण और पुराने फॉर्म में गलतियां सुधारना।",
    "card3-sub3": "<strong>दस्तावेज़ स्कैनिंग और PDF:</strong> जरूरी फाइलों को अच्छी क्वालिटी में स्कैन करना और सुरक्षित PDF बनाना।",
    "card3-footer-text": "सुरक्षित ऑनलाइन काम",
    "card3-footer-btn": "काम शुरू करवाएं",
    "process-badge": "हमारा प्रोसेस",
    "process-title": "हम कैसे काम करते हैं?",
    "process-desc": "आपका काम बिना किसी गलती के पूरा करने के लिए हमारा आसान 4-स्टेप तरीका।",
    "process-step1-title": "1. डॉक्यूमेंट शेयर करें",
    "process-step1-desc": "आप अपने जरूरी कागजात (आधार, पैन, फॉर्म-16) आसानी से व्हाट्सएप या सीधे ऑफिस में आकर हमें देते हैं।",
    "process-step2-title": "2. चेक करना और जांचना",
    "process-step2-desc": "हमारी टीम आपकी सभी डिटेल्स और फाइलों को ध्यान से चेक करती है ताकि कोई गलती न बचे।",
    "process-step3-title": "3. ऑनलाइन सबमिशन",
    "process-step3-desc": "हम सरकारी पोर्टल (EPFO या इनकम टैक्स साइट) पर आपका डेटा एकदम सही तरीके से अपलोड करते हैं।",
    "process-step4-title": "4. रसीद (Receipt) प्राप्त करें",
    "process-step4-desc": "काम होने के बाद रसीद (Acknowledgement Receipt) और जरूरी PDF सीधे आपके व्हाट्सएप पर भेज दी जाती है।",
    "creed-badge": "हमारा उद्देश्य",
    "creed-title": "हम आपके समय की कीमत समझते हैं।",
    "creed-desc": "हमारा मानना है कि सरकारी कागजी काम से बचना ही काफी नहीं है, बल्कि आपका कीमती समय बचाना भी जरूरी है ताकि आप बिना किसी तनाव के अपने काम पर ध्यान दे सकें।",
    "creed-quote": "\"हमारा लक्ष्य है बिना किसी गलती के आपका काम करना, ताकि सरकारी नोटिस या पेनल्टी का डर हमेशा के लिए खत्म हो जाए।\"",
    "creed-col1-num": "1",
    "creed-col2-num": "2",
    "creed-col3-num": "3",
    "creed-col4-num": "4",
    "creed-col1-title": "तेज़ काम (Fast Work)",
    "creed-col1-desc": "जैसे ही आप हमें डॉक्यूमेंट देते हैं, काम तुरंत शुरू हो जाता है। हमारे यहां कोई पेंडिंग काम नहीं छोड़ा जाता।",
    "creed-col2-title": "पूरी जांच (Double Check)",
    "creed-col2-desc": "सभी फॉर्म और पीएफ दावों को अपलोड करने से पहले दोबारा चेक किया जाता है ताकि कोई रिजेक्शन न आए।",
    "creed-col3-title": "भरोसा और ईमानदारी",
    "creed-col3-desc": "हमारा मुख्य ऑफिस उरई (उत्तर प्रदेश) में है, लेकिन हम ऑनलाइन माध्यम से पूरे देश के ग्राहकों का काम सफलता से कर रहे हैं।",
    "creed-col4-title": "नए नियमों की जानकारी",
    "creed-col4-desc": "सरकार समय-समय पर नियम बदलती रहती है। हम रोज नए अपडेट्स पर नजर रखते हैं ताकि आपको हमेशा सही जानकारी मिले।",
    "standing-badge": "हमारा भरोसा",
    "standing-title": "हमारा ऑफिस और लोगों का भरोसा",
    "standing-desc": "उरई के स्थानीय लोगों और देश भर के ग्राहकों को बेहतर सर्विस देने का गर्व। Google Maps पर हमारे पास 23+ अच्छे Reviews हैं।",
    "standing-card-title": "कौशल भाई मार्केट, रथ रोड, उरई",
    "standing-card-desc": "रथ रोड पर आसानी से मिलने वाला मार्केट",
    "standing-card-reviews": "23 सत्यापित गूगल रिव्यू",
    "contact-title": "सीधा संपर्क डेस्क (Advisory Desk)",
    "contact-addr-label": "कार्यालय का पता (Address)",
    "contact-addr-val": "अंशु कंप्यूटर और टैक्स कंसल्टेंसी<br/>कौशल मार्केट, रथ रोड, उरई,<br/>उत्तर प्रदेश - 285001",
    "contact-hours-label": "काम के घंटे (Timings)",
    "contact-hours-val": "सोमवार से शनिवार: सुबह 11:00 बजे से शाम 6:00 बजे तक",
    "contact-hours-sub": "रविवार और सरकारी छुट्टी के दिन बंद",
    "contact-email-label": "ईमेल (Email)",
    "contact-whatsapp-btn": "WhatsApp पर मैसेज भेजें",
    "contact-whatsapp-sub": "सामान्य वर्किंग ऑवर्स में आपको 30 मिनट के अंदर रिप्लाई मिल जाएगा।",
    "footer-desc": "एक विश्वसनीय टैक्स और पीएफ एजेंसी। हमारा संकल्प है अपने ग्राहकों का काम पूरी ईमानदारी और सटीकता से पूरा करना।",
    "footer-access-title": "शॉर्टकट लिंक्स",
    "footer-copyright": "© 2026 अंशु कंप्यूटर और टैक्स कंसल्टेंसी। सर्वाधिकार सुरक्षित।",
    "footer-national-badge": "विश्वसनीय टैक्स और पीएफ सलाहकार",
    "footer-loc-badge": "कौशल मार्केट, उरई, उत्तर प्रदेश",
    "toggle-lang-label": "English"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("hi");

  useEffect(() => {
    const saved = localStorage.getItem("preferred_lang") as Language;
    if (saved === "hi" || saved === "en") {
      setLanguage(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const nextLang = prev === "en" ? "hi" : "en";
      localStorage.setItem("preferred_lang", nextLang);
      document.documentElement.lang = nextLang;
      return nextLang;
    });
  };

  const t = (key: string) => {
    return simpleTranslations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
